name: Compile check

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  Compilation:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: make
      run: make
    - run: echo "Compiled Successfully"
    - name: make clean
      run: make clean
    - run: echo "clean rule present"
    - name: make fclean
      run: make fclean
    - run: echo "fclean present"
    - name: make re
      run: make re
    - run: echo "Recompiled Successfully"
